[package]
name = "dicom-ul"
version = "0.1.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>", "Paul Knopf <pauldotknopf@gmail.com>"]
description = "Types and methods for interacting with the DICOM Upper Layer Protocol"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["network-programming"]
keywords = ["dicom"]
readme = "README.md"

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[dependencies]
byteordered = "0.5.0"
dicom-encoding = { path = "../encoding/", version = "0.2.0" }
snafu = "0.6.8"

[dev-dependencies]
matches = "0.1.8"
